### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by weiki08** [eshengsky/iBlog#12]
出现下面的错误是为什么？

```
/node_modules/mongoose-schema-extend/index.js:28
        return () => target.concat(that.callQueue);
                ^

SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ec2-user/iBlog2/models/db.js:3:14)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ec2-user/iBlog2/models/category.js:1:72)
    at Module._compile (module.js:430:26)
```

**Comment by eshengsky** [comment]
启动时请加上参数--harmony-proxies
https://github.com/eshengsky/iBlog2#启动站点

**Comment by weiki08** [comment]
找到原因了，是node版本太低，不支持es6标准
