### ISSUE TITLE
所有环境搭建好后启动项目报错，错误如下，望指导，看着应该是mongodb的问题

### ISSUE THREAD

**Issue by jasonxu11** [eshengsky/iBlog#16]
@eshengsky 
``` javascript "D:\Program Files\JetBrains\WebStorm 2017.1.2\bin\runnerw.exe" "D:\Program Files\nodejs\node.exe" --debug-brk=56682 --expose_debug_as=v8debug "D:\code workspace\nodejs_workspace\iBlog2\bin\www"
Debugger listening on [::]:56682
‌‌base
D:\code workspace\nodejs_workspace\iBlog2\node_modules\_mongoose@4.9.8@mongoose\lib\services\model\applyHooks.js:34
    if (pair[0] !== 'pre' && pair[0] !== 'post' && pair[0] !== 'on') {
            ^

TypeError: Cannot read property '0' of undefined
    at applyHooks (D:\code workspace\nodejs_workspace\iBlog2\node_modules\_mongoose@4.9.8@mongoose\lib\services\model\applyHooks.js:34:13)
    at Function.compile (D:\code workspace\nodejs_workspace\iBlog2\node_modules\_mongoose@4.9.8@mongoose\lib\model.js:3636:3)
    at Mongoose.model (D:\code workspace\nodejs_workspace\iBlog2\node_modules\_mongoose@4.9.8@mongoose\lib\index.js:417:22)
    at Object.<anonymous> (D:\code workspace\nodejs_workspace\iBlog2\models\category.js:16:34)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\code workspace\nodejs_workspace\iBlog2\proxy\category.js:1:83)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

Process finished with exit code 1
 ```
从错误信息看应该是mongoose问题，我换成了mongoose@4.9.8（最新版）还是这个错，mongodb是能连接上的，希望帮忙看下谢谢。

**Comment by eshengsky** [comment]
@jasonxu11 是mongoose版本问题，请获取最新代码。
