### ISSUE TITLE
有个报错，请问怎么解决呢

### ISSUE THREAD

**Issue by Lyall-X** [eshengsky/iBlog#58]
TypeError: Cannot read property '_id' of null
    at category.getByAlias.then.cate (/home/liuyue/Blog/iBlog2/routes/blog.js:42:25)
点击标题报错

**Comment by Lyall-X** [comment]
以及
TypeError: Cannot read property 'IsActive' of null
    at Promise.all.then.results (/home/liuyue/Blog/iBlog2/routes/blog.js:134:21)

**Comment by eshengsky** [comment]
我本地无法复现。你是否手动修改过MongoDB的分类数据？
